openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
components:
  schemas:
    ContractLineGenerationRequest:
      type: object
      required:
        - orderIds
      description: Request to generate a Order, includes the Order ID
      properties:
        orderIds:
          type: array
          description: A list of record Ids for the Order
          items:
            type: string
    ContractLineGenerationResponse:
      type: object
      description: Response includes the record Id of the generated Order.
      properties:
        message:
          type: string
          description: A message for the generated Order
paths:
  /api/generateContractlines:
    post:
      operationId: generateContractLines
      summary: Generate a ContractItems for a given Order and Quote
      tags:
        - Contract Lines
      description: Create Contract lines.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ContractLineGenerationRequest"
      x-sfdc:
        heroku:
          authorization:
            connectedApp: HerokuGenerateContractItemApp
            permissionSet: HerokuGenerateContractItemPS
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContractLineGenerationResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                  message:
                    type: string
                    description: Error message when client context is missing or invalid
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                  message:
                    type: string
                    description: Error message when an unexpected error occurs
