openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
components:
  schemas:
    OrderLineGenerationRequest:
      type: object
      required:
        - orderId
      description: Request to generate a Order, includes the Order ID
      properties:
        orderId:
          type: string
          description: A record Id for the Order
        quoteId:
          type: string
          description: A list of record Ids for the Lines
    OrderLineGenerationResponse:
      type: object
      description: Response includes the record Id of the generated Order.
      properties:
        message:
          type: string
          description: A message for the generated Order
paths:
  /api/generateOrderlines:
    post:
      operationId: generateOrderLines
      summary: Generate a OrderItems for a given Order and Quote
      tags:
        - Order Lines
      description: Create Order lines.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderLineGenerationRequest"
      x-sfdc:
        heroku:
          authorization:
            connectedApp: HerokuGenerateOrderItemApp
            permissionSet: HerokuGenerateOrderItemPS
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderLineGenerationResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                  message:
                    type: string
                    description: Error message when client context is missing or invalid
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                  message:
                    type: string
                    description: Error message when an unexpected error occurs
